version: '3.7'

services:
  auth:
    build:
      context: ./auth
    ports:
      - 3000:3000
    command: npm start
    volumes:
      - zoo_auth_node_modules:/home/app/node_modules
      - ./auth:/home/app:delegated
    networks:
      - shared_bridge

volumes:
  zoo_auth_node_modules:

networks:
  shared_bridge:
    driver: bridge
